bamboo-specs-script

diff --git a/bamboo-specs/bamboo.yml b/bamboo-specs/bamboo.yml
--- a/bamboo-specs/bamboo.yml
+++ b/bamboo-specs/bamboo.yml
@@ -1,4 +1,3 @@
----
 version: 2
 plan:
     project-key: AUT
@@ -6,18 +5,68 @@ plan:
     key: MVN
 
 stages:
+    - Security Scan:
+        jobs:
+        - Vulnerability Scan
     - Build and Deploy:
         jobs:
         - Build and Package
-
+Vulnerability Scan:
+    tasks:
+    - script:
+        - |
+            echo "Running vulnerability scan..."
+            RESPONSE=$(curl --location "http://microservice-genai.uksouth.cloudapp.azure.com/api/vmsb/pipelines/initscan" \
+            --header "Content-Type: application/json" \
+            --data '{
+                "encrypted_user_id": "gAAAAABn0rtiUIre85Q28N4qZj7Ks30nAI8gukwzyeAengetWJ4CbZzfyQbgpP6wFXrXm0BROOwL4ps-uefe8pmcPDeergw7SA==",
+                "scanner_id": 1,
+                "target_branch": "main", 
+                "repo_url": "https://github.com/DatlaBharath/HelloService",
+                "pat": "${bamboo.authToken}"
+              }')
+            
+            echo "Curl response: $RESPONSE"
+            
+            ESCAPED_RESPONSE=$(echo "$RESPONSE" | sed 's/\"/\\\"/g')
+            JSON_DATA="{\"response\": \"$ESCAPED_RESPONSE\"}"
+            
+            CONTENT_LENGTH=${#JSON_DATA}
+            echo "Sending response to backend..."
+            curl -X POST http://ec2-13-201-18-57.ap-south-1.compute.amazonaws.com/app/save-curl-response-bamboo?sessionId=adminEC23C9F6-77AD-9E64-7C02-A41EF19C7CC3 \
+            -H "Content-Type: application/json" \
+            -H "Content-Length: $CONTENT_LENGTH" \
+            -d "$JSON_DATA"
+            
+            TOTAL_VULNERABILITIES=$(echo "$RESPONSE" | grep -o '"total_vulnerabilites":[^,}]*' | sed 's/"total_vulnerabilites"://g' | tr -d ' "')
+            HIGH=$(echo "$RESPONSE" | grep -o '"high":[^,}]*' | sed 's/"high"://g' | tr -d ' "')
+            MEDIUM=$(echo "$RESPONSE" | grep -o '"medium":[^,}]*' | sed 's/"medium"://g' | tr -d ' "')
+            echo "Total vulnerabilities: $TOTAL_VULNERABILITIES"
+            
+            if echo "$TOTAL_VULNERABILITIES" | grep -q '^[0-9][0-9]*$'; then
+                if [ "$HIGH" -le 0 ] && [ "$MEDIUM" -le 0 ]; then
+                    echo "Success: No high and medium vulnerabilities found."
+                else
+                    echo "Failure: Found $TOTAL_VULNERABILITIES vulnerabilities. $HIGH high vulnerabilities. $MEDIUM medium vulnerabilities"
+                    echo "Setting build result to FAILED"
+                    exit 1
+                fi
+            else
+                if echo "$RESPONSE" | grep -q '"success": *true'; then
+                    echo "Success status found in response. Proceeding with build."
+                else
+                    echo "Warning: Could not parse total_vulnerabilities and no success status found."
+                    echo "Continuing with build as a precaution, but please check the response."
+                fi
+            fi
 Build and Package:
     tasks:
     - script:
         - mvn clean install -DskipTests
-        - docker build -t ${bamboo.dockerUser}/helloservice-jenkins:${bamboo.buildNumber} .
+        - docker build -t ${bamboo.dockerUser}/helloservice:${bamboo.buildNumber} .
         - echo ${bamboo.dockerPass} | docker login -u ${bamboo.dockerUser} --password-stdin
-        - docker push ${bamboo.dockerUser}/helloservice-jenkins:${bamboo.buildNumber}
-
+        - docker push ${bamboo.dockerUser}/helloservice:${bamboo.buildNumber}
+        
     - script:
         - echo "Creating deployment.yaml"
         - |
@@ -38,12 +87,11 @@ Build and Package:
                 spec:
                   containers:
                   - name: helloservice
-                    image: ${bamboo.dockerUser}/helloservice-jenkins:${bamboo.buildNumber}
+                    image: ${bamboo.dockerUser}/helloservice:${bamboo.buildNumber}
                     ports:
                     - containerPort: 5000
             EOF
-
-    - script:
+        
         - echo "Creating service.yaml"
         - |
             cat <<EOF > service.yaml
@@ -60,7 +108,7 @@ Build and Package:
                 targetPort: 5000
                 nodePort: 30007
             EOF
-
+        
     - script:
         - echo "Deploying to Kubernetes"
         - scp -o StrictHostKeyChecking=no -i /var/test.pem deployment.yaml service.yaml ubuntu@3.110.105.96:/home/ubuntu/
